---
- name: copy script to opt
  copy: src=change_password.sh dest=/opt mode=755

- name: change password efemci, esad and epayment user
  command: "/opt/change_password.sh"
  
- name: delete script
  file: path=/opt/change_password.sh state=absent
